---

- name: "Debug dest"
  ansible.builtin.debug:
    msg: "{{ ansible_roles_src_dir }}/ansible-role-{{ meta_role_name }}/meta/main.yml"

- name: "Install ansible-lint"
  ansible.builtin.pip:
    name: ansible-lint
    state: present
    extra_args: "--user --upgrade"

- name: "Ensure that role and meta directory exist"
  ansible.builtin.file:
    path: "{{ ansible_roles_src_dir }}/ansible-role-{{ meta_role_name }}/meta"
    state: directory
    mode: "0755"

- name: "Generate meta/main.yml for role {{ meta_role_name }}"
  ansible.builtin.template:
    src: main.yml.j2
    dest: "{{ ansible_roles_src_dir }}/ansible-role-{{ meta_role_name }}/meta/main.yml"
    mode: "0755"
    validate: "ansible-lint %s"
