---
# name: ansible-roles
# file: inventory/host_vars/virtinstall.yml

meta_description: 'Ansible role for deploying libvirt guests with virt-install.'

meta_galaxy_tags:
  - virtinstall
  - libvirt

meta_year_created: '2022'

read_description: |-
  Perform unattended install of libvirt guests with virt-install.

read_references:
  - "[man virt-install(1)](https://manpages.org/virt-install)"

req_collections:
  - community.libvirt
  - name: git+https://github.com/jam82/ansible-collection-general
    version: main

reqs_roles:
  - name: git+https://github.com/jam82/ansible-role-libvirtd
    version: main

mole_scenarios:
  - scenario:
      name: local
      create_sequence:
        - create
        - prepare
      check_sequence:
        - cleanup
        - destroy
        - create
        - prepare
        - converge
        - check
        - destroy
      converge_sequence:
        - dependency
        - create
        - prepare
        - converge
      destroy_sequence:
        - cleanup
        - destroy
      test_sequence:
        - dependency
        - lint
        - cleanup
        - destroy
        - create
        - prepare
        - converge
        - idempotence
        - verify
        - cleanup
        - destroy
    dependency:
      name: galaxy
      options:
        requirements-file: requirements.yml
    driver:
      name: delegated
      options:
        managed: false
        ansible_connection_options:
          ansible_connection: local
    lint: set -e; ansible-lint
    platforms:
      - name: localhost
        ansible_connection: local
    provisioner:
      name: ansible
      log: true
      playbooks:
        prepare: ../resources/playbooks/prepare.yml
        converge: ../resources/playbooks/converge.yml
        verify: ../resources/playbooks/verify.yml
    verifier:
      name: ansible

mole_prepare:
  - name: "PLAYBOOK | Prepare"
    hosts: all
    become: false
    gather_facts: false
    tasks: []

mole_verify:
  - name: "PLAYBOOK | Verify"
    hosts: all
    become: false
    gather_facts: false
    tasks:
      - name: "Check virt-install version"
        ansible.builtin.command:
          cmd: "virt-install --version"
        register: _virtinstall_version
        changed_when: false
      - name: "Check virt-install --version return code"
        ansible.builtin.assert:
          that: _virtinstall_version.rc == 0
