---

nginx_group:
  hosts:
    nginx:
  vars:
    # --- meta/main.yml vars ---------------------------------------------------
    meta_role_name: nginx
    meta_role_description: "Ansible role for setting up nginx."
    # --- meta/requirements.yml ------------------------------------------------
    requirements_collections:
      - containers.podman
    requirements_roles: []
