---
# name: ansible-roles
# file: playbooks/tasks/github_query.yml

- name: "Retrieve repositories from GitHub"
  ansible.builtin.uri:
    url: "https://api.github.com/user/repos?type=owner&per_page=100&page={{ page }}"
    method: GET
    headers:
      Accept: "application/vnd.github.v3+json"
      Authorization: "{{ 'Bearer ' + gh_token }}"
    return_content: true
    validate_certs: true
  register: github_response

- name: "Check if the response is empty"
  ansible.builtin.set_fact:
    is_empty_response: "{{ github_response.json | length == 0 }}"

- name: "Add fetched repositories to the list"
  ansible.builtin.set_fact:
    all_repos: "{{ all_repos + github_response.json }}"
  when: not is_empty_response

- name: "Update the current page"
  ansible.builtin.set_fact:
    current_page: "{{ current_page + 1 }}"
  when: not is_empty_response

- name: "Recursively call the fetch task if there are more pages"
  ansible.builtin.include_tasks: github_fetch_repos.yml
  vars:
    page: "{{ current_page }}"
  when: not is_empty_response
