---
# name: ansible-roles
# file: playbooks/github_clone.yml

# - name: "Display repository names and descriptions"
#   ansible.builtin.debug:
#     msg: "Repository Name: {{ item.name }}, Description: {{ item.description }}"

- name: "Clone or update repository"  # noqa: latest[git]
  ansible.builtin.git:
    repo: "{{ item.ssh_url }}"
    dest: "{{ repo_path }}"
  changed_when: false

- name: "Check if dev branch was checked out"
  ansible.builtin.stat:
    path: "{{ repo_path }}/.git/refs/heads/dev"
  register: dev_branch

- name: "Checkout dev branch if it does exist"
  ansible.builtin.git:
    repo: "{{ item.ssh_url }}"
    dest: "{{ repo_path }}"
    version: dev
  changed_when: false
  when: dev_branch.stat.exists

- name: "Create and checkout dev branch if it does not exist" # noqa command-instead-of-module
  ansible.builtin.shell: |
    git pull
    git checkout -b dev
    git pull origin dev
    git push --set-upstream origin dev
  args:
    chdir: "{{ repo_path }}"
  when: not dev_branch.stat.exists
  changed_when: false
