---
# name: ansible-roles
# file: inventory/group_vars/all/meta_main.yml

# defaults for meta/meta_main.yml ----------------------------------------------

meta_role_name: "{{ inventory_hostname }}"
meta_repo_name: "ansible-role-{{ meta_role_name }}"
meta_role_description: 'Ansible role for setting up {{ meta_role_name }}.'
meta_author: Jonas Mauer
meta_allow_duplicates: false
meta_company: none
meta_galaxy_tags: []
meta_repo_url: "https://github.com/{{ meta_namespace }}/{{ meta_repo_name }}"
meta_issue_tracker_url: "{{ meta_repo_url }}/issues"
meta_license: MIT
meta_year_created: '2024'
meta_min_ansible_version: "2.15"
meta_namespace: jam82
meta_platforms:
  - { distribution: AlmaLinux, os_family: RedHat, tags: ['8', '9'] }
  - { distribution: Debian, os_family: Debian, tags: ['11', '12'] }
  - { distribution: Fedora, os_family: RedHat, tags: ['39', '40', 'rawhide'] }
  - { distribution: Ubuntu, os_family: Debian, tags: ['20.04', '22.04'] }
