---
# play: ansible-roles
# file: inventory/group_vars/all/paths.yml

# base dirctory of this role
base_directory: "~/src/ansible/ansible-roles"

# list of paths to be removed relative to role directory (ansible_host)
relative_paths_to_remove:
  - .ansible-lint.yml
  - .github/workflows
  - .travis.yml
  - .yamllint.yml
  - requirements.txt
  - requirements.yml
  - tasks.yml
  - tox.ini
