---
# name: ansible-roles
# file: inventory/group_vars/all/precommit.yml

# defaults for pre-commit-config.yml -------------------------------------------

meta_precommit_config:
  repos:
    - repo: https://github.com/ansible-community/ansible-lint
      rev: v24.2.0
      hooks:
        - id: ansible-lint
    - repo: https://github.com/commitizen-tools/commitizen
      rev: v3.15.0
      hooks:
        - id: commitizen
          stages: [commit-msg]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
        - id: detect-private-key
        - id: end-of-file-fixer
        - id: trailing-whitespace
