---
# name: ansible-roles
# file: inventory/group_vars/all/remove.yml

# defaults for remove.yml ------------------------------------------------------

# list of paths to be removed relative to role directory (ansible_host)
relative_paths_to_remove:
  - .ansible-lint.yml
  - .github
  - .travis.yml
  - .yamllint.yml
  - Makefile
  - requirements.txt
  - requirements.yml
  - tasks.yml
  - tox.ini
