---
# name: ansible-roles
# file: inventory/host_vars/certificates/molecule.yml

meta_molecule_playbooks:
    converge: ../resources/playbooks/converge.yml
    prepare: ../resources/playbooks/prepare.yml
    verify: ../resources/playbooks/verify.yml

meta_molecule_prepare: |
  - name: "PLAYBOOK | Prepare"
    hosts: host-certificates
    become: true
    gather_facts: true
    vars:
      certificates_ca_dir: "/etc/ssl/ca/example"
    tasks:
      - name: "Install packages"
        ansible.builtin.package:
          name:
            - apache2
            - git
            - make
            - openssl
          state: present
      - name: "Ensure CA directory exists"
        ansible.builtin.file:
          path: "{{ certificates_ca_dir }}"
          state: directory
          mode: "0755"
      - name: "Clone make-ca repository"
        ansible.builtin.git:
          repo: "https://github.com/jam82/make-ca.git"
          dest: "{{ certificates_ca_dir }}"
          version: main
      - name: "Run CA 'init' target"
        community.general.make:
          chdir: "{{ certificates_ca_dir }}"
          target: init
      - name: "Run 'fritzbox' target"
        community.general.make:
          chdir: "{{ certificates_ca_dir }}"
          target: certs/component-ca/server/fritzbox
      - name: "Copy certificates to /var/www/html"
        ansible.builtin.copy:
          src: "{{ certificates_ca_dir }}/pub/"
          dest: "/var/www/localhost/htdocs/"
          mode: "0644"
          remote_src: true
      - name: "Start webserver"
        ansible.builtin.service:
          name: apache2
          state: started
          enabled: true
