---
# name: ansible-roles
# file: playbooks/contributing.yml
# description: Clone GitHub repositories for 'gh_user_or_org' matching 'gh_query'

- name: "PLAYBOOK | Clone"
  hosts: localhost
  gather_facts: false
  vars:
    gh_user_or_org: "{{ lookup('env', 'GH_USER', default='') }}"
    gh_is_org: false
    gh_name: "{{ 'org:' if gh_is_org else 'user:' }}{{ gh_user_or_org }}"
    gh_token: "{{ lookup('env', 'GH_TOKEN', default='') }}"
    gh_query: "{{ lookup('env', 'QUERY', default='ansible-role-') }}"
  tasks:
    - name: "Lookup 'ansible-role-*' repositories on GitHub for {{ gh_user_or_org }}"
      ansible.builtin.uri:
        url: "https://api.github.com/search/repositories?q={{ gh_query }}+in:name+{{ gh_name }}"
        method: GET
        headers:
          Accept: "application/vnd.github.v3+json"
          Authorization: "{{ 'Bearer ' + gh_token if gh_token else omit }}"
        return_content: true
        validate_certs: true
      register: github_response

    - name: "Include the 'github_clone.yml' tasks for each repository found"
      vars:
        repo_path: "{{ role_directory }}/{{ item.name }}"
      ansible.builtin.include_tasks: tasks/github_clone.yml
      loop: "{{ github_response.json['items'] }}"
      loop_control:
        label: "{{ item.name }}"
      # exact matching as github api returns e.g. ansible-roles for gh_query=ansible-role-
      when: gh_query in item.name and item.owner.login == gh_user_or_org
