---
# name: ansible-roles
# file: playbooks/contributing.yml
# description: Clone GitHub repositories for 'gh_user_or_org' matching 'gh_query'

- name: "PLAYBOOK | Clone"
  hosts: localhost
  gather_facts: false
  vars:
    gh_token: "{{ lookup('env', 'GH_TOKEN', default='') }}"
    gh_query: "{{ lookup('env', 'QUERY', default='ansible-role-') }}"
  tasks:
    - name: "Initialize an empty list to collect repositories"
      ansible.builtin.set_fact:
        all_repos: []

    - name: "Define a variable for the current page"
      ansible.builtin.set_fact:
        current_page: 1

    - name: "Fetch repositories with pagination"
      ansible.builtin.include_tasks: tasks/github_fetch_repos.yml
      vars:
        page: "{{ current_page }}"

    - name: "Debug to /tmp/github_fetch_repos.json"
      ansible.builtin.copy:
        content: "{{ all_repos | json_query(query) | to_nice_json }}"
        dest: "/tmp/github_fetch_repos.json"
        mode: '0644'
      vars:
        query: "[?starts_with(name, `{{ gh_query }}`)].{name: name, full_name: full_name, ssh_url: ssh_url}"

    - name: "Set fact gh_repos"
      ansible.builtin.set_fact:
        gh_repos: "{{ all_repos | json_query(query) }}"
      vars:
        query: "[?starts_with(name, `{{ gh_query }}`)].{name: name, full_name: full_name, ssh_url: ssh_url}"

    # - name: "Include the 'github_clone.yml' tasks for each repository found"
    #   vars:
    #     repo_path: "{{ conf_role_dir }}/{{ item.name }}"
    #   ansible.builtin.include_tasks: tasks/github_clone.yml
    #   loop: "{{ gh_repos }}"
    #   loop_control:
    #     label: "{{ item.name }}"
