---
# name: ansible-roles
# file: playbooks/docs.yml

- name: "Playbook 'contributing' for role {{ meta_role_name }}"
  hosts: "{{ target | default('all') }}"
  become: false
  gather_facts: false
  tasks:
    - name: "Generate CONTRIBUTING.md"
      ansible.builtin.template:
        src: 'CONTRIBUTING.md.j2'
        dest: "{{ ansible_host }}/CONTRIBUTING.md"
        mode: "0644"
