---
# name: ansible-roles
# file: playbooks/meta.yml

- name: "PLAYBOOK | Meta"
  hosts: "{{ target | default('all') }}"
  become: false
  gather_facts: false
  tasks:
    - name: "Ensure that path exists"
      ansible.builtin.file:
        path: "{{ ansible_host }}/meta"
        state: directory
        mode: "0755"
    - name: "Generate meta/main.yml"
      ansible.builtin.template:
        src: "meta/main.yml.j2"
        dest: "{{ ansible_host }}/meta/main.yml"
        mode: "0644"
        validate: "ansible-lint %s"
    - name: "Generate meta/requirements.yml"
      ansible.builtin.template:
        src: "meta/requirements.yml.j2"
        dest: "{{ ansible_host }}/meta/requirements.yml"
        mode: "0644"
        validate: "ansible-lint %s"
