---
# name: ansible-roles
# file: playbooks/molecule.yml

- name: "Playbook 'molecule' for role {{ meta_role_name }}"
  hosts: "{{ target | default('all') }}"
  become: false
  gather_facts: false
  tasks:
    - name: "Ensure molecule directories exist"
      ansible.builtin.file:
        path: "{{ ansible_host }}/{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - molecule
        - molecule/all
        - molecule/default
        - molecule/resources
        - molecule/resources/playbooks

    - name: "Generate {{ item }}"
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "{{ ansible_host }}/{{ item }}"
        mode: "0644"
      loop:
        - molecule/all/molecule.yml
        - molecule/default/molecule.yml
        - molecule/resources/playbooks/converge.yml
        - molecule/resources/playbooks/prepare.yml
        - molecule/resources/playbooks/verify.yml
