---
# name: ansible-roles
# file: playbooks/molecule.yml

- name: "PLAYBOOK | Molecule"
  hosts: "{{ target | default('all') }}"
  become: false
  gather_facts: false
  tasks:
    - name: "Remove molecule directory"
      ansible.builtin.file:
        path: "{{ ansible_host }}/molecule"
        state: absent

    - name: "Ensure molecule directories exist"
      ansible.builtin.file:
        path: "{{ ansible_host }}/molecule/{{ item.scenario.name }}"
        state: directory
        mode: "0755"
      loop: "{{ mole_scenarios }}"

    - name: "Ensure molecule resource directories exist"
      ansible.builtin.file:
        path: "{{ ansible_host }}/{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - molecule/resources/playbooks

    - name: "Generate molecule ressources"
      ansible.builtin.template:
        src: "{{ item }}.yml.j2"
        dest: "{{ ansible_host }}/{{ item }}.yml"
        mode: "0644"
        validate: "ansible-lint %s"
      loop:
        - molecule/resources/playbooks/prepare
        - molecule/resources/playbooks/converge
        - molecule/resources/playbooks/verify

    - name: "Generate molecule scenarios"
      ansible.builtin.template:
        src: "molecule/molecule.yml.j2"
        dest: "{{ ansible_host }}/molecule/{{ item.scenario.name }}/molecule.yml"
        mode: "0644"
        validate: "ansible-lint %s"
      loop: "{{ mole_scenarios }}"
