---
# name: ansible-roles
# file: playbooks/pyproject.yml

- name: "Playbook 'pyproject' for role {{ meta_role_name }}"
  hosts: "{{ target | default('all') }}"
  become: false
  gather_facts: false
  tasks:
    - name: "Set fact 'meta_release_version'"
      ansible.builtin.set_fact:
        meta_release_version: "{{ lookup('jam82.dev.github_version', \
          lookup('ansible.builtin.env', 'GH_TOKEN'), meta_namespace, meta_role_name) }}"

    - name: "Generate pyproject.toml"
      ansible.builtin.template:
        src: 'pyproject.toml.j2'
        dest: "{{ ansible_host }}/pyproject.toml"
        mode: "0644"
