---
# name: ansible-roles
# file: playbooks/readme.yml

- name: "PLAYBOOK | README"
  hosts: "{{ target | default('all') }}"
  become: false
  gather_facts: false
  tasks:
    - name: "Generate README.md file"
      ansible.builtin.template:
        src: 'README.md.j2'
        dest: "{{ ansible_host }}/README.md"
        mode: "0644"
