---
# name: ansible-roles
# file: playbooks/remove.yml

- name: "PLAYBOOK | Remove"
  hosts: "{{ target | default('all') }}"
  become: false
  gather_facts: false
  tasks:
    - name: "Remove configured paths from 'remove'"
      ansible.builtin.file:
        path: "{{ ansible_host }}/{{ item }}"
        state: absent
      loop: "{{ remove }}"
