---
# name: ansible-roles
# file: playbooks/remove.yml

- name: "Playbook 'remove' for role {{ meta_role_name }}"
  hosts: "{{ target | default('all') }}"
  become: false
  gather_facts: false
  tasks:
    - name: "Remove configured paths from 'relative_paths_to_remove'"
      ansible.builtin.file:
        path: "{{ ansible_host }}/{{ item }}"
        state: absent
      loop: "{{ relative_paths_to_remove }}"
