---
# play: ansible-roles
# file: playbooks/requirements.yml

- name: "Gsenerate requirements.yml in base and meta for roles inventory"
  hosts: all
  become: false
  gather_facts: true
  tasks:
    - name: "Ensure that role and meta directory exist"
      ansible.builtin.file:
        path: "{{ relative_role_path }}/meta"
        state: directory
        mode: "0755"

    - name: "Install ansible-lint"
      ansible.builtin.pip:
        name: ansible-lint
        state: present
        extra_args: "--user --upgrade"

    - name: "Generate meta/requirements.yml for ansible-galaxy metadata in role {{ meta_role_name }}"
      ansible.builtin.template:
        src: "{{ base_directory }}/templates/requirements.yml.j2"
        dest: "{{ relative_role_path }}/meta/requirements.yml"
        mode: "0755"
